diem_danh/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('logout','Controller@logout') -> name('logout');

Route::group(['middleware' => 'CheckLogin'],function()
{
	Route::group(['middleware' => 'CheckGiaoVu'],function()
	{

		Route::group(['frefix' => 'GiaoVien','as' =>'GiaoVien.'],function(){
			Route::get('giao_vien','GiaoVienController@view_all') -> name('view_all');
			Route::get('giao_vien/view_insert','GiaoVienController@view_insert') -> name('view_insert');
			Route::post('giao_vien/process_insert','GiaoVienController@process_insert') -> name('process_insert');
			Route::get('giao_vien/view_update/{ma}','GiaoVienController@view_update') -> name('view_update');
			Route::post('giao_vien/update/{ma}','GiaoVienController@update') -> name('update');
			Route::get('giao_vien/delete/{ma}','GiaoVienController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'nganh_hoc','as' =>'nganh_hoc.'],function(){
			Route::get('nganh_hoc','NganhHocController@view_all') -> name('view_all');
			Route::get('nganh_hoc/view_insert','NganhHocController@view_insert') -> name('view_insert');
			Route::post('nganh_hoc/process_insert','NganhHocController@process_insert') -> name('process_insert');
			Route::get('nganh_hoc/view_update/{ma}','NganhHocController@view_update') -> name('view_update');
			Route::post('nganh_hoc/update/{ma}','NganhHocController@update') -> name('update');
			Route::get('nganh_hoc/delete/{ma}','NganhHocController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'khoa','as' =>'khoa.'],function(){
			Route::get('khoa','KhoaController@view_all') -> name('view_all');
			Route::get('khoa/view_insert','KhoaController@view_insert') -> name('view_insert');
			Route::post('khoa/process_insert','KhoaController@process_insert') -> name('process_insert');
			Route::get('khoa/view_update/{ma}','KhoaController@view_update') -> name('view_update');
			Route::post('khoa/update/{ma}','KhoaController@update') -> name('update');
			Route::get('khoa/delete/{ma}','KhoaController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'mon_hoc','as' =>'mon_hoc.'],function(){
			Route::get('mon_hoc','MonHocController@view_all') -> name('view_all');
			Route::get('mon_hoc/view_insert','MonHocController@view_insert') -> name('view_insert');
			Route::post('mon_hoc/process_insert','MonHocController@process_insert') -> name('process_insert');
			Route::get('mon_hoc/view_update/{ma}','MonHocController@view_update') -> name('view_update');
			Route::post('mon_hoc/update/{ma}','MonHocController@update') -> name('update');
			Route::get('mon_hoc/delete/{ma}','MonHocController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'lop','as' =>'lop.'],function(){
			Route::get('lop','LopController@view_all') -> name('view_all');
			Route::get('lop/view_insert','LopController@view_insert') -> name('view_insert');
			Route::post('lop/process_insert','LopController@process_insert') -> name('process_insert');
			Route::get('lop/view_update/{ma}','LopController@view_update') -> name('view_update');
			Route::post('lop/update/{ma}','LopController@update') -> name('update');
			Route::get('lop/delete/{ma}','LopController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'sinh_vien','as' =>'sinh_vien.'],function(){
			Route::get('sinh_vien','SinhVienController@view_all') -> name('view_all');
			Route::get('ajax','SinhVienController@ajax') -> name('ajax');
			Route::get('ajax_lop','SinhVienController@ajax_lop') -> name('ajax_lop');
			Route::get('excel','SinhVienController@insert_excel') -> name('insert_excel');
			Route::get('sinh_vien/view_insert','SinhVienController@view_insert') -> name('view_insert');
			Route::post('sinh_vien/process_insert','SinhVienController@process_insert') -> name('process_insert');
			Route::post('sinh_vien/excel','SinhVienController@process_excel') -> name('process_excel');
			Route::get('sinh_vien/view_update/','SinhVienController@view_update') -> name('view_update');
			Route::post('sinh_vien/update/{ma}','SinhVienController@update') -> name('update');
			Route::get('sinh_vien/delete/{ma}','SinhVienController@delete') -> name('delete');
		});
		Route::group(['frefix' => 'tai_khoan','as' =>'tai_khoan.'],function(){
			Route::get('tai_khoan','TaiKhoanController@thong_tin') -> name('thong_tin');
		});
	});

	Route::group(['frefix' => 'phan_cong','as' =>'phan_cong.'],function(){
		Route::get('phan_cong','PhanCongController@view_all') -> name('view_all') ->middleware('CheckGiaoVu');
		Route::get('phan_cong_gv','PhanCongController@gv_phan_cong') -> name('gv_phan_cong') ->middleware('CheckGiaoVien');
		Route::get('phan_cong/view_insert','PhanCongController@view_insert') -> name('view_insert') -> middleware('CheckGiaoVu');
		Route::post('phan_cong/process_insert','PhanCongController@process_insert') -> name('process_insert') ->middleware('CheckGiaoVu');
		Route::get('phan_cong/view_update/{ma}','PhanCongController@view_update') -> name('view_update') ->middleware('CheckGiaoVu');
		Route::post('phan_cong/update/{ma}','PhanCongController@update') -> name('update') -> middleware('CheckGiaoVu');
		Route::get('phan_cong/delete/{ma}','PhanCongController@delete') -> name('delete') -> middleware('CheckGiaoVu');
	});

	Route::group(['frefix' => 'diem_danh','as' =>'diem_danh.'],function(){
		Route::get('diem_danh','DiemDanhController@view_all') -> name('view_all');
		Route::post('diem_danh','DiemDanhController@view_diem_danh') -> name('view_diem_danh');
		Route::get('view_insert','DiemDanhController@view_insert') -> name('view_insert');
		Route::post('process_diem_danh','DiemDanhController@process_diem_danh') -> name('process_diem_danh');
		Route::get('view_update/{ma}','DiemDanhController@view_update') -> name('view_update');
		Route::post('update/{ma}','DiemDanhController@update') -> name('update');
		Route::get('delete/{ma}','DiemDanhController@delete') -> name('delete');
	});


	Route::get('giao_vu','Controller@giao_vu') -> name('giao_vu') -> middleware('CheckGiaoVu');
	Route::get('trang_giao_vien','Controller@giao_vien') -> name('giao_vien')-> middleware('CheckGiaoVien');
});
Route::get('','Controller@view_login')->name('view_login');
Route::post('process_login','Controller@process_login') -> name('process_login');

diem_danh/resources/views/layout/sidebar/sidebar-gv.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="sidebar-menu">
        <!-- Left Menu Start -->
        <ul class="metismenu list-unstyled" id="side-menu">
            <li class="menu-title">MENU</li>


           <li>
                <a href="javascript: void(0);" class="has-arrow waves-effect">
                    <i class="ti-clipboard"></i>
                    <span> Điểm Danh </span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    <li><a href="{{ route('diem_danh.view_all') }}">Điểm Danh</a></li>
                    <li><a href="email-read.html">Lịch Sử Điểm Danh</a></li>
                </ul>
            </li>

            <li>
                <a href="{{ route('phan_cong.gv_phan_cong') }}">
                    <i class="mdi mdi-calendar-check"></i>
                    <span> Lịch Phân Công </span>
                </a>
            </li>
        </ul>
    </div>
</body>
</html>

diem_danh/resources/views/layout/sidebar/sidebar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
     <div id="sidebar-menu">
        <!-- Left Menu Start -->
        <ul class="metismenu list-unstyled" id="side-menu">
            <li class="menu-title">MENU</li>
            <li>
                <a href="javascript: void(0);" class="waves-effect">
                    <span class="badge badge-pill badge-primary float-right"></span>
                    <i class="ion ion-md-school"></i>
                    <span> Sinh Viên </span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    <li><a href="{{ route('sinh_vien.view_insert') }}">Thêm Sinh Viên</a></li>
                    <li><a href="{{ route('sinh_vien.insert_excel') }}">Thêm Sinh Viên Bằng Excel </a></li>

                    <li><a href="{{ route('sinh_vien.view_all') }}">Danh Sách Sinh Viên</a></li>
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);" class="waves-effect">
                    <span class="badge badge-pill badge-primary float-right"></span>
                    <i class="dripicons-user"></i>
                    <span> Giáo Viên </span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    <li><a href="{{ route('GiaoVien.view_insert') }}">Đăng Kí</a></li>
                    <li><a href="{{ route('phan_cong.view_all') }}">Phân Công</a></li>
                    <li><a href="{{ route('GiaoVien.view_all') }}">Danh Sách Giáo Viên</a></li>
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);" class="waves-effect">
                    <span class="badge badge-pill badge-primary float-right"></span>
                    <i class="mdi mdi-view-dashboard"></i>
                    <span> Liên Khóa </span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    <li><a href="{{ route('khoa.view_insert') }}">Thêm Khóa</a></li>
                    <li><a href="{{ route('khoa.view_all') }}">Danh Sách Liên Khóa</a></li>
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);" class="waves-effect">
                    <span class="badge badge-pill badge-primary float-right"></span>
                    <i class="mdi mdi-home-edit"></i>
                    <span> Lớp Học </span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    <li><a href="{{ route('lop.view_insert') }}">Thêm Lớp</a></li>
                    <li><a href="{{ route('lop.view_all') }}">Danh Sách Lớp</a></li>
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);" class="waves-effect">
                    <span class="badge badge-pill badge-primary float-right"></span>
                    <i class="mdi mdi-flask-outline"></i>
                    <span> Ngành Học </span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    <li><a href="{{ route('nganh_hoc.view_insert') }}">Thêm Ngành</a></li>
                    <li><a href="{{ route('nganh_hoc.view_all') }}">Danh Sách Ngành Học</a></li>
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);" class="waves-effect">
                    <span class="badge badge-pill badge-primary float-right"></span>
                    <i class="mdi mdi-buffer"></i>
                    <span> Môn Học </span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    <li><a href="{{ route('mon_hoc.view_insert') }}">Thêm Môn Học</a></li>
                    <li><a href="{{ route('mon_hoc.view_all') }}">Danh Sách Môn Học</a></li>
                </ul>
            </li>
        </ul>
    </div>
</body>
</html>