diem_danh/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('logout','Controller@logout') -> name('logout');

Route::group(['middleware' => 'CheckLogin'],function()
{
	Route::group(['middleware' => 'CheckGiaoVu'],function()
	{

		Route::group(['frefix' => 'GiaoVien','as' =>'GiaoVien.'],function(){
			Route::get('giao_vien','GiaoVienController@view_all') -> name('view_all');
			Route::get('giao_vien/view_insert','GiaoVienController@view_insert') -> name('view_insert');
			Route::post('giao_vien/process_insert','GiaoVienController@process_insert') -> name('process_insert');
			Route::get('giao_vien/view_update/{ma}','GiaoVienController@view_update') -> name('view_update');
			Route::post('giao_vien/update/{ma}','GiaoVienController@update') -> name('update');
			Route::get('giao_vien/delete/{ma}','GiaoVienController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'nganh_hoc','as' =>'nganh_hoc.'],function(){
			Route::get('nganh_hoc','NganhHocController@view_all') -> name('view_all');
			Route::get('nganh_hoc/view_insert','NganhHocController@view_insert') -> name('view_insert');
			Route::post('nganh_hoc/process_insert','NganhHocController@process_insert') -> name('process_insert');
			Route::get('nganh_hoc/view_update/{ma}','NganhHocController@view_update') -> name('view_update');
			Route::post('nganh_hoc/update/{ma}','NganhHocController@update') -> name('update');
			Route::get('nganh_hoc/delete/{ma}','NganhHocController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'khoa','as' =>'khoa.'],function(){
			Route::get('khoa','KhoaController@view_all') -> name('view_all');
			Route::get('khoa/view_insert','KhoaController@view_insert') -> name('view_insert');
			Route::post('khoa/process_insert','KhoaController@process_insert') -> name('process_insert');
			Route::get('khoa/view_update/{ma}','KhoaController@view_update') -> name('view_update');
			Route::post('khoa/update/{ma}','KhoaController@update') -> name('update');
			Route::get('khoa/delete/{ma}','KhoaController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'mon_hoc','as' =>'mon_hoc.'],function(){
			Route::get('mon_hoc','MonHocController@view_all') -> name('view_all');
			Route::get('mon_hoc/view_insert','MonHocController@view_insert') -> name('view_insert');
			Route::post('mon_hoc/process_insert','MonHocController@process_insert') -> name('process_insert');
			Route::get('mon_hoc/view_update/{ma}','MonHocController@view_update') -> name('view_update');
			Route::post('mon_hoc/update/{ma}','MonHocController@update') -> name('update');
			Route::get('mon_hoc/delete/{ma}','MonHocController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'lop','as' =>'lop.'],function(){
			Route::get('lop','LopController@view_all') -> name('view_all');
			Route::get('lop/view_insert','LopController@view_insert') -> name('view_insert');
			Route::post('lop/process_insert','LopController@process_insert') -> name('process_insert');
			Route::get('lop/view_update/{ma}','LopController@view_update') -> name('view_update');
			Route::post('lop/update/{ma}','LopController@update') -> name('update');
			Route::get('lop/delete/{ma}','LopController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'sinh_vien','as' =>'sinh_vien.'],function(){
			Route::get('sinh_vien','SinhVienController@view_all') -> name('view_all');
			Route::get('ajax','SinhVienController@ajax') -> name('ajax');
			Route::get('ajax_lop','SinhVienController@ajax_lop') -> name('ajax_lop');
			Route::get('excel','SinhVienController@insert_excel') -> name('insert_excel');
			Route::get('sinh_vien/view_insert','SinhVienController@view_insert') -> name('view_insert');
			Route::post('sinh_vien/process_insert','SinhVienController@process_insert') -> name('process_insert');
			Route::post('sinh_vien/excel','SinhVienController@process_excel') -> name('process_excel');
			Route::get('sinh_vien/view_update/','SinhVienController@view_update') -> name('view_update');
			Route::post('sinh_vien/update/{ma}','SinhVienController@update') -> name('update');
			Route::get('sinh_vien/delete/{ma}','SinhVienController@delete') -> name('delete');
		});
		Route::group(['frefix' => 'tai_khoan','as' =>'tai_khoan.'],function(){
			Route::get('tai_khoan','TaiKhoanController@thong_tin') -> name('thong_tin');
		});
	});

	Route::group(['frefix' => 'phan_cong','as' =>'phan_cong.'],function(){
		Route::get('phan_cong','PhanCongController@view_all') -> name('view_all') ->middleware('CheckGiaoVu');
		Route::get('phan_cong_gv','PhanCongController@gv_phan_cong') -> name('gv_phan_cong') ->middleware('CheckGiaoVien');
		Route::get('phan_cong/view_insert','PhanCongController@view_insert') -> name('view_insert') -> middleware('CheckGiaoVu');
		Route::post('phan_cong/process_insert','PhanCongController@process_insert') -> name('process_insert') ->middleware('CheckGiaoVu');
		Route::get('phan_cong/view_update/{ma}','PhanCongController@view_update') -> name('view_update') ->middleware('CheckGiaoVu');
		Route::post('phan_cong/update/{ma}','PhanCongController@update') -> name('update') -> middleware('CheckGiaoVu');
		Route::get('phan_cong/delete/{ma}','PhanCongController@delete') -> name('delete') -> middleware('CheckGiaoVu');
	});

	Route::group(['frefix' => 'diem_danh','as' =>'diem_danh.'],function(){
		Route::get('diem_danh','DiemDanhController@view_all') -> name('view_all');
		Route::post('diem_danh','DiemDanhController@view_diem_danh') -> name('view_diem_danh');
		Route::get('view_insert','DiemDanhController@view_insert') -> name('view_insert');
		Route::post('process_diem_danh','DiemDanhController@process_diem_danh') -> name('process_diem_danh');
		Route::get('view_update/{ma}','DiemDanhController@view_update') -> name('view_update');
		Route::post('update/{ma}','DiemDanhController@update') -> name('update');
		Route::get('delete/{ma}','DiemDanhController@delete') -> name('delete');
	});


	Route::get('giao_vu','Controller@giao_vu') -> name('giao_vu') -> middleware('CheckGiaoVu');
	Route::get('trang_giao_vien','Controller@giao_vien') -> name('giao_vien')-> middleware('CheckGiaoVien');
});
Route::get('','Controller@view_login')->name('view_login');
Route::post('process_login','Controller@process_login') -> name('process_login');

diem_danh/app/Models/GiaoVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GiaoVien extends Model
{
    protected $table = 'giao_vien';
    protected $fillable = [
    	'ho_ten',
    	'email',
    	'password'
    ];
    public $timestamps = false;
    protected $primaryKey = 'ma';
}

diem_danh/app/Http/Controllers/GiaoVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\GiaoVien;
use Illuminate\Support\Facades\DB;


class GiaoVienController extends Controller
{
    public function view_all()
    {
    	$array_giao_vien = GiaoVien::get();
    	return view('giao_vien.view_all',compact('array_giao_vien'));
    }
    public function view_insert()
    {
    	return view('giao_vien.view_insert');
    }
    public function process_insert(Request $rq)
    {   
        GiaoVien::create($rq -> all());
    	return redirect('giao_vien');
    }
    public function view_update($ma,Request $rq)
    {
    	$giao_vien = GiaoVien::find($ma);
    	return view('giao_vien.view_update',compact('giao_vien'));
    }
    public function update($ma,Request $rq)
    {
    	GiaoVien::find($ma) -> update($rq -> all());
    	return redirect('GiaoVien');
    }
    public function delete($ma)
    {
    	GiaoVien::destroy($ma);
    	return redirect('GiaoVien');
    }
}

diem_danh/resources/views/giao_vien/view_all.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	@extends('layout.master.master')

	@section('content')
	<h1>Danh sách giáo viên</h1>
	<a href="{{ route('GiaoVien.view_insert') }}">Đăng kí tài khoản giáo viên</a>
	<table border="1" width="50%" class="table">
		<tr>
			<th>Họ tên</th>
			<th>Giới tính</th>
			<th>Ngày sinh</th>
			<th>Địa chỉ</th>
			<th>Số điện thoại</th>
			<th>Email</th>
			<th>Xửa</th>
			<th>Xóa</th>
		</tr>
		@foreach ($array_giao_vien as $giao_vien)
			<tr>
				<td>
					{{ $giao_vien -> ho_ten }}
				</td>
				<td>
					{{ $giao_vien -> gioi_tinh }}
				</td>
				<td>
					{{ $giao_vien -> ngay_sinh }}
				</td>
				<td>
					{{ $giao_vien -> que_quan}}
				</td>
				<td>
					{{ $giao_vien -> so_dien_thoai }}
				</td>
				<td>
					{{ $giao_vien -> email }}
				</td>
				<td>
					<a href="{{ route('GiaoVien.view_update',['ma' => $giao_vien->ma]) }}">Sửa</a>
				</td>
				<td>
					<a href="{{ route('GiaoVien.delete',['ma' => $giao_vien->ma]) }}">Xóa</a>
				</td>
			</tr>
		@endforeach
	</table>
@endsection
</body>
</html>

diem_danh/resources/views/giao_vien/view_insert.blade.php
@extends('layout.master.master')

@section('content')
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h3>Đăng Kí Tài Khoản Cho Giáo Viên</h3>
	<br>
	<form method="POST" action="{{ route('GiaoVien.process_insert') }}">
		{{ csrf_field() }}
		Họ tên
		<input type="text" name="ho_ten">
		<br>
		Email
		<input type="email" name="email">
		<br>
		Password
		<input type="password" name="password">
		<br>
		<button>Đăng kí</button>
	</form>
</body>
</html>
@endsection

diem_danh/resources/views/giao_vien/view_update.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h3>sửa thông tin</h3>
	<form method="POST" action="{{ route('GiaoVien.update',['ma' => $giao_vien -> ma]) }}">
		{{ csrf_field() }}
		Họ tên
		<input type="text" name="ho_ten" value="{{ $giao_vien -> ho_ten }}">
		<br>
		Giới tính
		<input type="checkbox" name="gioi_tinh" value ="0" 
		@if ($giao_vien -> gioi_tinh == 0)
			checked 
		@endif>Nam
		<input type="checkbox" name="gioi_tinh" value ="1" 
		@if ($giao_vien -> gioi_tinh ==1)
			checked 
		@endif
		>Nữ
		<br>
		Ngày sinh
		<input type="date" name="ngay_sinh" value="{{ $giao_vien -> ngay_sinh }}">
		<br>
		Đỉa chỉ
		<input type="text" name="que_quan" value="{{ $giao_vien -> que_quan }}">
		<br>
		Số điện thoại
		<input type="text" name="so_dien_thoai" value="{{ $giao_vien -> so_dien_thoai }}">
		<br>
		Email
		<input type="email" name="email" value="{{ $giao_vien -> email }}">
		<br>
		Password
		<input type="password" name="password" value="{{ $giao_vien -> password }}">
		<br>
		<button>sửa</button>
	</form>
</body>
</html>