diem_danh/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('logout','Controller@logout') -> name('logout');

Route::group(['middleware' => 'CheckLogin'],function()
{
	Route::group(['middleware' => 'CheckGiaoVu'],function()
	{

		Route::group(['frefix' => 'GiaoVien','as' =>'GiaoVien.'],function(){
			Route::get('giao_vien','GiaoVienController@view_all') -> name('view_all');
			Route::get('giao_vien/view_insert','GiaoVienController@view_insert') -> name('view_insert');
			Route::post('giao_vien/process_insert','GiaoVienController@process_insert') -> name('process_insert');
			Route::get('giao_vien/view_update/{ma}','GiaoVienController@view_update') -> name('view_update');
			Route::post('giao_vien/update/{ma}','GiaoVienController@update') -> name('update');
			Route::get('giao_vien/delete/{ma}','GiaoVienController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'nganh_hoc','as' =>'nganh_hoc.'],function(){
			Route::get('nganh_hoc','NganhHocController@view_all') -> name('view_all');
			Route::get('nganh_hoc/view_insert','NganhHocController@view_insert') -> name('view_insert');
			Route::post('nganh_hoc/process_insert','NganhHocController@process_insert') -> name('process_insert');
			Route::get('nganh_hoc/view_update/{ma}','NganhHocController@view_update') -> name('view_update');
			Route::post('nganh_hoc/update/{ma}','NganhHocController@update') -> name('update');
			Route::get('nganh_hoc/delete/{ma}','NganhHocController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'khoa','as' =>'khoa.'],function(){
			Route::get('khoa','KhoaController@view_all') -> name('view_all');
			Route::get('khoa/view_insert','KhoaController@view_insert') -> name('view_insert');
			Route::post('khoa/process_insert','KhoaController@process_insert') -> name('process_insert');
			Route::get('khoa/view_update/{ma}','KhoaController@view_update') -> name('view_update');
			Route::post('khoa/update/{ma}','KhoaController@update') -> name('update');
			Route::get('khoa/delete/{ma}','KhoaController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'mon_hoc','as' =>'mon_hoc.'],function(){
			Route::get('mon_hoc','MonHocController@view_all') -> name('view_all');
			Route::get('mon_hoc/view_insert','MonHocController@view_insert') -> name('view_insert');
			Route::post('mon_hoc/process_insert','MonHocController@process_insert') -> name('process_insert');
			Route::get('mon_hoc/view_update/{ma}','MonHocController@view_update') -> name('view_update');
			Route::post('mon_hoc/update/{ma}','MonHocController@update') -> name('update');
			Route::get('mon_hoc/delete/{ma}','MonHocController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'lop','as' =>'lop.'],function(){
			Route::get('lop','LopController@view_all') -> name('view_all');
			Route::get('lop/view_insert','LopController@view_insert') -> name('view_insert');
			Route::post('lop/process_insert','LopController@process_insert') -> name('process_insert');
			Route::get('lop/view_update/{ma}','LopController@view_update') -> name('view_update');
			Route::post('lop/update/{ma}','LopController@update') -> name('update');
			Route::get('lop/delete/{ma}','LopController@delete') -> name('delete');
		});

		Route::group(['frefix' => 'sinh_vien','as' =>'sinh_vien.'],function(){
			Route::get('sinh_vien','SinhVienController@view_all') -> name('view_all');
			Route::get('ajax','SinhVienController@ajax') -> name('ajax');
			Route::get('ajax_lop','SinhVienController@ajax_lop') -> name('ajax_lop');
			Route::get('excel','SinhVienController@insert_excel') -> name('insert_excel');
			Route::get('sinh_vien/view_insert','SinhVienController@view_insert') -> name('view_insert');
			Route::post('sinh_vien/process_insert','SinhVienController@process_insert') -> name('process_insert');
			Route::post('sinh_vien/excel','SinhVienController@process_excel') -> name('process_excel');
			Route::get('sinh_vien/view_update/','SinhVienController@view_update') -> name('view_update');
			Route::post('sinh_vien/update/{ma}','SinhVienController@update') -> name('update');
			Route::get('sinh_vien/delete/{ma}','SinhVienController@delete') -> name('delete');
		});
		Route::group(['frefix' => 'tai_khoan','as' =>'tai_khoan.'],function(){
			Route::get('tai_khoan','TaiKhoanController@thong_tin') -> name('thong_tin');
		});
	});

	Route::group(['frefix' => 'phan_cong','as' =>'phan_cong.'],function(){
		Route::get('phan_cong','PhanCongController@view_all') -> name('view_all') ->middleware('CheckGiaoVu');
		Route::get('phan_cong_gv','PhanCongController@gv_phan_cong') -> name('gv_phan_cong') ->middleware('CheckGiaoVien');
		Route::get('phan_cong/view_insert','PhanCongController@view_insert') -> name('view_insert') -> middleware('CheckGiaoVu');
		Route::post('phan_cong/process_insert','PhanCongController@process_insert') -> name('process_insert') ->middleware('CheckGiaoVu');
		Route::get('phan_cong/view_update/{ma}','PhanCongController@view_update') -> name('view_update') ->middleware('CheckGiaoVu');
		Route::post('phan_cong/update/{ma}','PhanCongController@update') -> name('update') -> middleware('CheckGiaoVu');
		Route::get('phan_cong/delete/{ma}','PhanCongController@delete') -> name('delete') -> middleware('CheckGiaoVu');
	});

	Route::group(['frefix' => 'diem_danh','as' =>'diem_danh.'],function(){
		Route::get('diem_danh','DiemDanhController@view_all') -> name('view_all');
		Route::post('diem_danh','DiemDanhController@view_diem_danh') -> name('view_diem_danh');
		Route::get('view_insert','DiemDanhController@view_insert') -> name('view_insert');
		Route::post('process_diem_danh','DiemDanhController@process_diem_danh') -> name('process_diem_danh');
		Route::get('view_update/{ma}','DiemDanhController@view_update') -> name('view_update');
		Route::post('update/{ma}','DiemDanhController@update') -> name('update');
		Route::get('delete/{ma}','DiemDanhController@delete') -> name('delete');
	});


	Route::get('giao_vu','Controller@giao_vu') -> name('giao_vu') -> middleware('CheckGiaoVu');
	Route::get('trang_giao_vien','Controller@giao_vien') -> name('giao_vien')-> middleware('CheckGiaoVien');
});
Route::get('','Controller@view_login')->name('view_login');
Route::post('process_login','Controller@process_login') -> name('process_login');

diem_danh/app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SinhVien extends Model
{
    protected $table = 'sinh_vien';
    protected $fillable = [
    	'ho_ten',
    	'gioi_tinh',
    	'ngay_sinh',
    	'dia_chi',
    	'so_dien_thoai',
    	'email',
    	'ma_lop'
    ];
    public $timestamps = false;
    protected $primaryKey = 'ma';

    public function lop()
    {
    	return $this -> belongsTo('App\Models\Lop','ma_lop');
    }

    public function getTenGioiTinhAttribute($gioi_tinh)
    {
        if ($this -> gioi_tinh == 0){
            return "Nam";
        }
        else{
            return "Nữ";
        }
    }
}

diem_danh/app/Http/Controllers/SinhVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SinhVien;
use App\Models\Lop;
use App\Models\NganhHoc;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\SinhVienImport;


class SinhVienController extends Controller
{
    public function view_all()
    {
        $array_nganh = NganhHoc::get();
    	$array_sinh_vien = DB::table('lop')
    	-> join('sinh_vien','sinh_vien.ma_lop','=','lop.ma')
    	-> join('nganh_hoc','nganh_hoc.ma','=','lop.ma_nganh_hoc')
    	-> join('khoa','khoa.ma','=','lop.ma_khoa')
    	-> get();
    	return view('sinh_vien.view_all',compact('array_sinh_vien','array_nganh'));
    }

    public function ajax(Request $rq)
    {
        $ma_nganh_hoc = $rq -> get('ma_nganh');
        $array_lop = Lop::where('ma_nganh_hoc', $ma_nganh_hoc )
        ->join('khoa','khoa.ma','lop.ma_khoa') 
        ->select('lop.ma','ten_lop','khoa.ten_khoa')
        -> get();
        return $array_lop;
    }

    public function ajax_lop(Request $rq)
    {
        $ma_lop = $rq -> get('ma_lop');
        $array_sinh_vien = SinhVien::where('ma_lop', $ma_lop ) -> get();
        return $array_sinh_vien;
    }

    public function view_insert()
    {
        $lop = Lop::get();
    	return view('sinh_vien.view_insert',compact('lop'));
    }

    public function insert_excel()
    {
        return view('sinh_vien.insert_excel');
    }
    public function process_insert(Request $rq)
    {
    	SinhVien::create($rq -> all());
    	return redirect('sinh_vien');
    }
    public function process_excel(Request $rq)
    {
        Excel::import(new SinhVienImport, $rq -> file_excel);
        return redirect('sinh_vien');
    }
    public function view_update($ma, Request $rq)
    {
        $lop = Lop::get();
    	$sinh_vien = SinhVien::find($ma);
    	return view('sinh_vien.view_update',compact('sinh_vien','lop'));
    }
    public function update($ma,Request $rq)
    {
    	SinhVien::find($ma) -> update($rq -> all());
    	//return redirect('sinh_vien');
    }
    public function delete($ma)
    {
    	SinhVien::destroy($ma);
    	return redirect('sinh_vien');
    }
}

diem_danh/resources/views/sinh_vien/insert_excel.blade.php
@extends('layout.master.master')

@section('content')
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h3>Thêm Sinh Viên Bằng File Excel</h3>
	<br>
	<form method="POST" enctype="multipart/form-data" action="{{ route('sinh_vien.process_excel') }}">
		{{ csrf_field() }}
		Chọn file exel:
		<input type="file" name="file_excel"  accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" class="dz-default dz-message">
		<br>
		<br>
		<button class="btn btn-primary waves-effect waves-light">Thêm</button>
	</form>
</body>
</html>
@endsection

diem_danh/resources/views/sinh_vien/view_all.blade.php
@extends('layout.master.master')

@section('content')

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript" src="{{ asset('js/jquery.js') }}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$('#nganh_hoc').change(function() {
				var ma_nganh_hoc = $(this).val();
				$.ajax({
					url: '{{ route('sinh_vien.ajax') }}',
					type: 'GET',
					dataType: 'json',
					data: {ma_nganh:ma_nganh_hoc},
				})
				.done(function(response) {
					$("#lop").html('');
					$("#lop").append('<option selected disabled >---Chọn---</option>');
					$(response).each(function() {
						$("#lop").append(`
							<option value='${this.ma}'> ${this.ten_lop} ${this.ten_khoa	} </option>
						`);
					});
				})
				.fail(function() {
					console.log("error");
				})
			});
			$('#lop').change(function() {
				var ma_lop = $(this).val();
				$.ajax({
					url: '{{ route('sinh_vien.ajax_lop') }}',
					type: 'GET',
					dataType: 'json',
					data: {ma_lop: ma_lop},
				})
				.done(function(response) {
					$("#sinh_vien").html('');
					$("#sinh_vien").append(`
						<tr>
							<th>Họ tên</th>
							<th>Giới tính</th>
							<th>Ngày sinh</th>
							<th>Đỉa chỉ</th>
							<th>Số điện thoại</th>
							<th>Email</th>
							<th>Sửa</th>
							<th>Xóa</th>
						</tr>
					`);
					$(response).each(function() {
						$("#sinh_vien").append(`
								<tr>
									<td>
										${this.ho_ten}
									</td>
									<td>
										${this.gioi_tinh}
									</td>
									<td>
										${this.ngay_sinh}
									</td>
									<td>
										${this.dia_chi}
									</td>
									<td>
										${this.so_dien_thoai}
									</td>
									<td>
										${this.email}
									</td>
								</tr>
						`);
					});
				})
				.fail(function() {
					console.log("error");
				})
			});
		});
	</script>
</head>
<body>
	<h3>Danh Sách Sinh Viên</h3>
<div>
	<div class="form-group">	
		<label>Ngành Học</label>
		<select name ="ma_nganh_hoc" class="form-control" id="nganh_hoc" style="width: 30%;">
			<option disabled selected >
				<span>---Chọn---</span>
			</option>
			@foreach ($array_nganh as $nganh)
				<option value="{{ $nganh -> ma }}">
					{{ $nganh -> ten_nganh_hoc }}
				</option>
			@endforeach
		</select>
	</div>
	<div class="form-group">	
		<label>lớp</label>
		<select name = "ma_lop" class="form-control" id="lop" style="width: 30%;">
			<option selected disabled >---Chọn---</option>
		</select>
	</div>
</div>
<br>
<table class=" table" id="sinh_vien">
	{{-- <tr>
		<th>Họ tên</th>
		<th>Giới tính</th>
		<th>Ngày sinh</th>
		<th>Đỉa chỉ</th>
		<th>Số điện thoại</th>
		<th>Email</th>
		<th>Sửa</th>
		<th>Xóa</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{ $sinh_vien -> ho_ten }}
			</td>
			<td>
				{{ $sinh_vien -> gioi_tinh }}
			</td>
			<td>
				{{ $sinh_vien -> ngay_sinh }}
			</td>
			<td>
				{{ $sinh_vien -> dia_chi }}
			</td>
			<td>
				{{ $sinh_vien -> so_dien_thoai }}
			</td>
			<td>
				{{ $sinh_vien -> email }}
			</td>
			<td>
				{{ $sinh_vien -> ten_lop }}{{ $sinh_vien -> ten_khoa }}
			</td>
			<td>
				{{ $sinh_vien -> ten_nganh_hoc }}
			</td>
			<td>
				<a href="{{ route('sinh_vien.view_update',['ma' => $sinh_vien -> ma]) }}">Sửa</a>
			</td>
		</tr>
	@endforeach --}}
</table>
</body>
</html>
@endsection

diem_danh/resources/views/sinh_vien/view_insert.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	@extends('layout.master.master')

	@section('content')
	<form method="POST" action="{{ route('sinh_vien.process_insert') }}" class="custom-validation">
		{{ csrf_field() }}
		<h3 style="text-align: center;">Thêm sinh viên</h3>
		<br>
		<div class="form-group">
			<label>Họ Tên</label>
			<input class="form-control" type="text" name="ho_ten" >
		</div>

		<div class="form-group">	
			<label>Giới Tính</label> &nbsp;&nbsp;&nbsp;
			<input class="" type="radio" name="gioi_tinh" value ="0">&nbsp;Nam&nbsp;&nbsp;
			<input class="" type="radio" name="gioi_tinh" value ="1">&nbsp;Nữ
		</div>

		<div class="form-group">
			<label>Ngày Sinh</label>
			<input class="form-control" type="date" name="ngay_sinh">
		</div>

		<div class="form-group">
			<label>Địa Chỉ</label>
			<input class="form-control" type="text" name="dia_chi">	
		</div>

		<div class="form-group">
			<label>Số Điện Thoại</label>
			<input class="form-control" type="text" name="so_dien_thoai">
		</div>

		<div class="form-group">	
			<label>Email</label>
			<input class="form-control" type="email" name="email">
		</div>
		<div class="form-group">	
			<label>lớp</label>
			<select name = "ma_lop" class="form-control">
				<option selected >--Chọn--</option>
				@foreach ($lop as $lop)
					<option value="{{ $lop -> ma }}">
						{{ $lop -> ten_lop }}
					</option>
				@endforeach
			</select>
		</div>
		<button class="btn btn-primary waves-effect waves-light mr-1">Thêm</button>
	</form>
	@endsection
</body>
</html>

diem_danh/resources/views/sinh_vien/view_update.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	@extends('layout.master.master')

	@section('content')
	<h3>sửa thông tin</h3>
	<form method="POST" action="{{ route('sinh_vien.update',['ma' => $sinh_vien -> ma]) }}" class="table">
		{{ csrf_field() }}
		<table >
			<tr>
				<th>Họ tên</th>
				<th>Giới tính</th>
				<th>Ngày sinh</th>
				<th>Đỉa chỉ</th>
				<th>Số điện thoại</th>
				<th>email</th>
				<th>Lớp</th>
			</tr>
			<tr>
				<td>
					<input type="text" name="ho_ten" value="{{ $sinh_vien -> ho_ten }}">
				</td>
				<td>
					<input type="radio" name="gioi_tinh" value ="0" 
					@if ($sinh_vien -> gioi_tinh == 0)
						checked 
					@endif>Nam &ensp;
					<input type="radio" name="gioi_tinh" value ="1" 
					@if ($sinh_vien -> gioi_tinh ==1)
						checked 
					@endif
					>Nữ
				</td>
				<td>
					<input type="date" name="ngay_sinh" value="{{ $sinh_vien -> ngay_sinh }}">
				</td>
				<td>
					<input type="text" name="so_dien_thoai" value="{{ $sinh_vien -> so_dien_thoai }}">
				</td>
				<td>
					<input type="text" name="dia_chi" value="{{ $sinh_vien -> dia_chi }}">
				</td>
				<td>
					<input type="email" name="email" value="{{ $sinh_vien -> email }}">
				</td>
				<td>
					<select name = "ma_lop">
					@foreach ($lop as $array_lop)
						<option value="{{ $array_lop -> ma}}" 
							@if ($sinh_vien -> ma  == $array_lop -> ma )
							selected
						@endif>{{ $array_lop -> ten_lop }}</option>
					@endforeach
					</select>
				</td>
			</tr>
		</table>
		<button>sửa</button>
	</form>
@endsection
</body>
</html>